"""
Deployment steps: register_model, deploy_agent
"""

import datetime
import json
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from zenml import step

from .training import AgentManifest
from .evaluation import EvalReport, SliceReport, ComparisonResult

PROJECT_ROOT = Path(__file__).parent.parent.parent
REGISTRY_PATH = PROJECT_ROOT / "model_registry.json"


# ---------------------------------------------------------------------------
# Dataclass
# ---------------------------------------------------------------------------

@dataclass
class ModelVersion:
    version: str
    timestamp: str
    eval_scores: dict
    slice_scores: dict
    is_champion: bool
    deployed_at: str | None
    traffic_percent: int        # canary starts at 10%, promotes to 50% then 100%


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

@step
def register_model(
    eval_report: EvalReport,
    slice_report: SliceReport,
    comparison_result: ComparisonResult,
    gate_passed: bool,
) -> ModelVersion:
    """Append this run to model_registry.json. Promote to champion if gate passed."""
    timestamp = datetime.datetime.utcnow().isoformat() + "Z"

    if REGISTRY_PATH.exists():
        with open(REGISTRY_PATH) as f:
            registry = json.load(f)
        versions = registry.get("versions", [])
        last = versions[-1]["version"] if versions else "1.0.0"
        major, minor, patch = map(int, last.split("."))
        new_version = f"{major}.{minor + 1}.{patch}"
    else:
        registry = {"champion": None, "versions": []}
        new_version = "1.0.0"

    def _get(obj, key):
        return obj[key] if isinstance(obj, dict) else getattr(obj, key)

    eval_scores = {_get(r, "name"): round(_get(r, "score"), 3) for r in _get(eval_report, "eval_results")}
    slice_scores = {
        name: round(data["score"], 3)
        for name, data in _get(slice_report, "slices").items()
    }

    model_version = ModelVersion(
        version=new_version,
        timestamp=timestamp,
        eval_scores=eval_scores,
        slice_scores=slice_scores,
        is_champion=gate_passed,
        deployed_at=timestamp if gate_passed else None,
        traffic_percent=10 if gate_passed else 0,
    )

    registry["versions"].append({
        "version":       new_version,
        "timestamp":     timestamp,
        "eval_scores":   {**eval_scores, "worst_slice": round(_get(slice_report, "worst_score"), 3)},
        "slice_scores":  slice_scores,
        "is_champion":   gate_passed,
        "deployed_at":   timestamp if gate_passed else None,
        "traffic_percent": model_version.traffic_percent,
    })
    if gate_passed:
        registry["champion"] = new_version

    with open(REGISTRY_PATH, "w") as f:
        json.dump(registry, f, indent=2)

    print(f"\nModel registry")
    print(f"  Version      : {new_version}")
    print(f"  Champion     : {'yes' if gate_passed else 'no'}")
    print(f"  Traffic      : {model_version.traffic_percent}%  (canary)")
    print(f"  Registry     : {REGISTRY_PATH}")

    return model_version


@step
def deploy_agent(manifest: AgentManifest, version: ModelVersion, gate_passed: bool) -> str:
    """Copy agent files, write traffic_split.json, start canary server at 10% traffic."""
    if not gate_passed:
        return ""

    deployed_dir = PROJECT_ROOT / "deployed"
    deployed_dir.mkdir(exist_ok=True)

    shutil.copy2(PROJECT_ROOT / "agent" / "customer_ops_agent.py", deployed_dir)
    shutil.copy2(PROJECT_ROOT / ".env", deployed_dir / ".env")

    # Canary traffic split config
    traffic_split = {
        "champion_version": version.version,
        "canary_percent":   version.traffic_percent,
        "stable_percent":   100 - version.traffic_percent,
        "promotion_stages": [10, 50, 100],
        "promote_on": {
            "min_healthy_minutes": 30,
            "max_error_rate":      0.01,
        },
        "rollback_on": {
            "max_error_rate":     0.05,
            "max_latency_p99_ms": 2000,
        },
    }
    with open(deployed_dir / "traffic_split.json", "w") as f:
        json.dump(traffic_split, f, indent=2)

    # FastAPI server
    server_code = '''\
"""FastAPI server — Customer Operations Agent (auto-generated by deploy step)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI
from pydantic import BaseModel
from customer_ops_agent import run_query

app = FastAPI(title="Customer Ops Agent", version="1.0.0")


class QueryRequest(BaseModel):
    query: str
    session_id: str | None = None


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "model": "claude-haiku-4-5-20251001"}


@app.post("/query")
def query_endpoint(req: QueryRequest) -> dict:
    return run_query(req.query, req.session_id)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
    server_path = deployed_dir / "server.py"
    server_path.write_text(server_code)

    endpoint = "http://localhost:8000"

    venv_python = PROJECT_ROOT / ".venv" / "bin" / "python"
    python_exe = str(venv_python) if venv_python.exists() else sys.executable

    try:
        subprocess.run(
            [python_exe, "-m", "pip", "install", "fastapi", "uvicorn", "-q"],
            check=True, capture_output=True,
        )
        proc = subprocess.Popen(
            [python_exe, str(server_path)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            cwd=str(deployed_dir),
        )
        time.sleep(2)
        status = f"PID {proc.pid}" if proc.poll() is None else "exited early"
        print(f"\n  Server started ({status}) → {endpoint}")
    except Exception as exc:
        print(f"\n  Could not auto-start server ({exc}). Run: python {server_path}")

    print(f"\nDeployment")
    print(f"  Version      : {version.version}")
    print(f"  Canary       : {version.traffic_percent}% traffic")
    print(f"  Files        : {deployed_dir}")
    print(f"  Traffic cfg  : {deployed_dir / 'traffic_split.json'}")
    print(f"  Endpoint     : {endpoint}")

    return endpoint
